backend:
  name: github
  repo: correioolindense/correioolindense.github.io
  branch: main
  base_url: https://decap-oauth-provider.onrender.com   # <<< troque para a URL do Render
  auth_endpoint: auth

site_url: https://correioolindense.com.br
display_url: https://correioolindense.com.br

# Biblioteca de mídia aponta para sua pasta de imagens
media_folder: "assets/images"
public_folder: "/assets/images"

publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true

    # cria o arquivo em _posts/ANO/mes/dia/AAAA-MM-DD-slug.md
    path: "{{year}}/{{fields.mes_extenso}}/{{day}}/{{year}}-{{month}}-{{day}}-{{slug}}"
    slug: "{{slug}}"
    preview_path: "{{slug}}"

    fields:
      # front matter conforme seu tema
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Categorias", name: "categories", widget: "list", hint: "Ex.: [ Olinda, Cidades ]" }
      - { label: "Data", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss ZZ", hint: "Ex.: 2025-09-11 12:30:00 -0300" }
      # Campo HIDDEN para converter mês numérico para extenso
      - { 
          label: "Mês por extenso", 
          name: "mes_extenso", 
          widget: "hidden", 
          default: "{% raw %}{{month | format_mes}}{% endraw %}" 
        }
      - { 
          label: "Imagem (capa)", 
          name: "image", 
          widget: "image",
          media_folder: "assets/images/{{year}}/{% raw %}{{month | format_mes}}{% endraw %}/{{day}}",
          public_folder: "/assets/images/{{year}}/{% raw %}{{month | format_mes}}{% endraw %}/{{day}}"
        }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Páginas"
    folder: "_pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "string", default: "page", required: false }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }