backend:
  name: github
  repo: correioolindense/correioolindense.github.io
  branch: main
  base_url: https://decap-oauth-provider.onrender.com   # <<< troque para a URL do Render
  auth_endpoint: /auth

site_url: https://correioolindense.com.br
display_url: https://correioolindense.com.br

# Biblioteca de mídia aponta para sua pasta de imagens
media_folder: "assets/images"
public_folder: "/assets/images"

publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true

    # cria o arquivo em _posts/ANO/mes/dia/AAAA-MM-DD-slug.md
    path: "{{fields.ano}}/{{fields.mes}}/{{fields.dia}}/{{year}}-{{month}}-{{day}}-{{slug}}"
    slug: "{{slug}}"
    preview_path: "{{slug}}"

    fields:
      - { label: "Ano (YYYY)", name: "ano", widget: "string", pattern: ["^\\d{4}$", "Use 4 dígitos"], hint: "Ex.: 2025" }
      - label: "Mês (português)"
        name: "mes"
        widget: "select"
        options: [janeiro, fevereiro, março, abril, maio, junho, julho, agosto, setembro, outubro, novembro, dezembro]
        default: setembro
      - { label: "Dia (DD)", name: "dia", widget: "string", pattern: ["^\\d{2}$", "Use 2 dígitos"], hint: "Ex.: 11" }

      # front matter conforme seu tema
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Categorias", name: "categories", widget: "list", hint: "Ex.: [ Olinda, Cidades ]" }
      - { label: "Imagem (capa)", name: "image", widget: "image", hint: "Salve em assets/images/ANO/mês/dia/arquivo.jpg" }
      - { label: "Data", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss ZZ", hint: "Ex.: 2025-09-11 12:30:00 -0300" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Páginas"
    folder: "_pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "string", default: "page", required: false }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }